# Required 
ThreshType: 'global' 
SampleNumber: 10 

# Global Parameters 
percentile_or_value: 'percentile' 
percentile: 50 
percentileLow: 25 
percentileHigh: 75 
value: 5 
valueLow: 5 
valueHigh: 5 

# Local Parameters 
EnoughSamples: 'no' 
LocalThresholdType: 'MinMaxMean' 

ref: 'MT_recon_2_2_entrez.mat' 
WorkingDir: '/workingdir/'
DataDir: '/workingdir/Data/'
TempDataDir: '/workingdir/TempData/'
LibDir: '/workingdir/Library/'
IndexDir: '/workingdir/Library/Bowtie2_Index/'
ScriptsDir: '/opt/PinAPL-Py/Scripts/'
AlignDir: '/workingdir/Alignments/'
AnalysisDir: '/workingdir/Analysis/'
TrimLogDir: '/workingdir/Analysis/Read_Trimming'
HitDir: '/workingdir/Analysis/sgRNA_Rankings'
GeneDir: '/workingdir/Analysis/Gene_Rankings'
ControlDir: '/workingdir/Analysis/Control/'
HeatDir: '/workingdir/Analysis/Heatmap/'
AlnQCDir: '/workingdir/Analysis/Alignment_Statistics/'
CountQCDir: '/workingdir/Analysis/ReadCount_Statistics/'
ScatterDir: '/workingdir/Analysis/ReadCount_Scatterplots/'
HiLiteDir: '/workingdir/Analysis/ReadCount_Scatterplots/Highlighted_Genes/'
CorrelDir: '/workingdir/Analysis/Replicate_Correlation/'
HiLiteDir2: '/workingdir/Analysis/Replicate_Correlation/Highlighted_Genes'
EffDir: '/workingdir/Analysis/sgRNA_Efficacy/'
DepthDir: '/workingdir/Analysis/Read_Depth/'
SeqQCDir: '/workingdir/Analysis/Sequence_Quality/'
pvalDir: '/workingdir/Analysis/p-values/' 
LogFileDir: '/workingdir/Analysis/Log_File/'
bw2Dir: '/usr/bin/'
CutAdaptDir: '/root/.local/bin/'   
STARSDir: '/opt/PinAPL-Py/Scripts/STARS_mod/'

SanityScript: 'CheckCharacters'
IndexScript: 'BuildLibraryIndex'
LoaderScript: 'LoadDataSheet'
ReadDepthScript: 'PlotNumReads'
SeqQCScript: 'CheckSequenceQuality'
TrimScript: 'TrimReads'
AlignScript: 'AlignReads'
NormalizeScript: 'NormalizeReadCounts'
AverageCountsScript: 'AverageCounts'
StatsScript: 'AnalyzeReadCounts'
ControlScript: 'AnalyzeControl'
sgRNARankScript: 'FindHits'
GeneRankScript: 'RankGenes'
CombineScript: 'CombineGeneRanks'
ScatterScript: 'PlotCounts'
ReplicateScript: 'PlotReplicates'
ClusterScript: 'PlotHeatmap'
